CREATE OR REPLACE VIEW VW_USER_RELATION AS
	SELECT
		MU.USERID AS USERID,
		MDU.DISCORDUSERID AS DISCORDUSERID,
		MMU.MISSKEYUSERID AS MISSKEYUSERID
	FROM
		MST_USER MU
	LEFT OUTER JOIN MST_DISCORD_USER MDU
		ON MU.USERID = MDU.USERID
	LEFT OUTER JOIN MST_MISSKEY_USER MMU
		ON MU.USERID = MMU.USERID
WITH READ ONLY;