CREATE OR REPLACE PACKAGE PKG_MISSKEY AS
	-- DiscordからMisskeyへ移行
	PROCEDURE TRANSFER_FROM_DISCORD(IN_USERID IN NUMBER, IN_DISCORDUSERID IN NUMBER);
END;
/

CREATE OR REPLACE PACKAGE BODY PKG_MISSKEY AS
	PROCEDURE TRANSFER_FROM_DISCORD(IN_USERID IN NUMBER, IN_DISCORDUSERID IN NUMBER) IS
		CURSOR CUR_DISCORD_USER(I_DUSERID IN NUMBER) IS
			SELECT
				USERID
			FROM
				MST_DISCORD_USER
			WHERE
				DISCORDUSERID = I_DUSERID
		;
		M_USERID NUMBER(12);
	BEGIN
		FOR rec IN CUR_DISCORD_USER(IN_DISCORDUSERID) LOOP
			-- USERIDの取得
			M_USERID := rec.USERID;

			-- 感情テーブルの更新
			UPDATE TBL_EMOTION
			SET USERID = IN_USERID
			WHERE USERID = M_USERID;

			-- DISCORDの更新
			UPDATE MST_DISCORD_USER
			SET USERID = IN_USERID
			WHERE DISCORDUSERID = IN_DISCORDUSERID;

			-- 最初の1回だけ実行する
			EXIT;
		END LOOP;
	
	-- マテリアライズドビューの強制リフレッシュ
	DBMS_MVIEW.REFRESH('MV_EMOTION', '?');
	
	END TRANSFER_FROM_DISCORD;

END PKG_MISSKEY;
/