CREATE MATERIALIZED VIEW MV_EMOTION
REFRESH FAST
START WITH SYSDATE
NEXT SYSDATE + ((1/24/60) * 30)
AS
SELECT
	BOTID,
	USERID,
	SUM(EMOTIONVALUE) AS EMOTIONSUM
FROM
	TBL_EMOTION
GROUP BY
	BOTID,
	USERID
;