CREATE TABLE MST_DISCORD_USER(
	DISCORDUSERID NUMBER(20) NOT NULL,
	USERNAME NVARCHAR2(64) NOT NULL,
	MENTION VARCHAR2(64) NOT NULL,
	USERID NUMBER(12),
	PRIMARY KEY(DISCORDUSERID),
	FOREIGN KEY(USERID) REFERENCES MST_USER(USERID),
	UNIQUE(USERID)
);