CREATE TABLE MST_MISSKEY_USER(
	MISSKEYUSERID VARCHAR2(64) NOT NULL,
	USERNAME NVARCHAR2(64) NOT NULL,
	USERID NUMBER(12),
	PRIMARY KEY(MISSKEYUSERID),
	FOREIGN KEY(USERID) REFERENCES MST_USER(USERID),
	UNIQUE(USERID)
);