CREATE TABLE TBL_EMOTION(
	EMOTIONID NUMBER(12) DEFAULT SEQ_TBL_EMOTION.NEXTVAL NOT NULL,
	BOTID VARCHAR2(32) NOT NULL,
	USERID NUMBER(12) NOT NULL,
	EMOTIONVALUE NUMBER(10) DEFAULT 0 NOT NULL,
	CREATEDAT DATE DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY(EMOTIONID),
	FOREIGN KEY(BOTID) REFERENCES MST_BOT(BOTID),
	FOREIGN KEY(USERID) REFERENCES MST_USER(USERID)
);