GRANT CREATE SESSION TO BOTMANAGER;

GRANT CREATE TABLE TO BOTMANAGER;

GRANT CREATE VIEW TO BOTMANAGER;

GRANT CREATE MATERIALIZED VIEW TO BOTMANAGER;

GRANT CREATE SEQUENCE TO BOTMANAGER;

GRANT CREATE PROCEDURE TO BOTMANAGER;

GRANT CREATE TRIGGER TO BOTMANAGER;

GRANT CREATE SYNONYM TO BOTMANAGER;

GRANT CREATE JOB TO BOTMANAGER;